# built on top of end-4's theme
# added some useless colored blocks in the terminal

# Don't print a new line at the start of the prompt
add_newline = true
# Pipes â•°â”€ â•­â”€
# Powerline symbols Â î‚° î‚± î‚² î‚³ î‚´ î‚µ î‚¶ î‚· î‚¸ î‚¹ î‚º î‚» î‚¼ î‚½ î‚¾ î‚¿ îƒ€ îƒ îƒ‚ îƒƒ îƒ„ îƒ… îƒ† îƒ‡ îƒˆ îƒŠ  îƒŒ îƒ îƒ îƒ îƒ îƒ‘ îƒ” îƒ’
# Wedges ğŸ­§ğŸ­’ ğŸ­£ğŸ­§ğŸ­“ ğŸ­‚ ğŸ­ƒ ğŸ­„ ğŸ­ˆ ğŸ­‰ ğŸ­ ğŸ­ŠğŸ­ ğŸ­Ÿ
# Random noise ğŸ¬–ğŸ¬¥ğŸ¬”ğŸ¬—

# format = """
# $cmd_duration$username$hostname $directory $git_branch
# $character
# """
format = """
$character$directory$git_branch
"""

# Replace the "â¯" symbol in the prompt with "ï¡", cool zap "ïƒ§"
[character] # The name of the module we are configuring is "character"
success_symbol = "[ï¡](bold fg:#a1ddff)"
error_symbol = "[ï¡](bold fg:#ff6868)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
style = ""
symbol = ""
# truncation_length = 4
truncation_symbol = ""
format = "[$symbol$branch(:$remote_branch)](bold fg:#83b4ff) "

[git_commit]
commit_hash_length = 4
tag_symbol = "ï’¶ "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
conflicted = " ğŸ³ "
ahead = " ğŸğŸ’¨ "
behind = " ğŸ˜° "
diverged = " ğŸ˜µ "
untracked = " ğŸ¤· â€"
stashed = " ğŸ“¦ "
modified = " ğŸ“ "
staged = '[++\($count\)](green)'
renamed = " âœï¸ "
deleted = " ï‡¸ "

[hostname]
ssh_only = false
format = "[$hostname](bg:#a9c2ff bold fg:black)[ğŸ­ŠğŸ­](bg:#a9c2ff fg:#a1ddff)"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"

[time]
disabled = true
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold bg:#6893ff fg:black"
style_root = "red bold"
format = "[ ğŸ­…](bold fg:#6893ff)[$user]($style)[ğŸ­ŠğŸ­](bg:#6893ff fg:#a9c2ff)"
disabled = false
show_always = true

[directory]
home_symbol = "~"
read_only = " ï‘– "
style = "fg:#6893ff"
truncation_length = 1
truncation_symbol = ""           # it's empty
format = '[$path](bold $style) '


[directory.substitutions]
# "Desktop" = "ï„ˆ"
# "Documents" = "ï»"
# "Downloads" = "ï‰"
# "Music" = "ï‹«"
# "Pictures" = "ï"
# "Videos" = "ï”¬"

[cmd_duration]
min_time = 0
format = '[î‚¶](bold fg:yellow)[î­± $duration](bold bg:yellow fg:black)[î‚´](bold fg:yellow) â€¢â€¢ '
